const EMAIL_JS_SERVICE_ID = process.env.EMAIL_JS_SERVICE_ID;
const EMAIL_JS_TEMPLATE_ID = process.env.EMAIL_JS_TEMPLATE_ID;
const EMAIL_JS_PUBLIC_KEY = process.env.EMAIL_JS_PUBLIC_KEY;
export {EMAIL_JS_SERVICE_ID,EMAIL_JS_TEMPLATE_ID,EMAIL_JS_PUBLIC_KEY};